string name

string settings_topic
string navpose_topic
string save_data_topic
string[] data_products
string[] data_product_topics
string[] data_product_image_topics


string pkg_name
string group_name
string node_name
string app_file
string app_path   
string[] rui_files_list
string rui_main_file
string rui_main_class  
string rui_menu_name

string description
string license_type
string license_link

bool active_state
bool running_state
int32 order
string msg_str




