string app_name

string display_name
string description

string node_name
string namespace

string settings_topic
string navpose_topic
string save_data_topic
string[] data_products
string[] data_product_topics
string[] data_product_image_topics


string pkg_name
string group_name

string app_file
string app_path   

string[] rui_files_list
string rui_main_file
string rui_main_class  

string license_type
string license_link

bool enabled
bool running
int32 order
string msg_str



