# Crosshair data

string name
string msg_str

# Ratio image min to max 
float32 x_ratio
float32 y_ratio

# Calculated pixel for current image size
int32 x_pixel
int32 y_pixel

# Calculated degree offsets for current image settings from center
float32 x_offset_deg
float32 y_offset_deg

# Calculated pixel offsets for current image size from center
int32 x_offset_pixel
int32 y_offset_pixel


# Crosshair Overlay Color
int32 r
int32 g
int32 b
