
string[] ai_frameworks

string[] ai_models
string[] ai_models_names
string[] ai_models_frameworks
string[] ai_models_types
bool[] ai_models_states

string[] active_ai_frameworks
string[] active_ai_frameworks_folders

string[] active_ai_models
string[] active_ai_models_names
string[] active_ai_models_frameworks
string[] active_ai_models_types
string[] active_ai_models_nodes
string[] active_ai_models_namespaces


string all_namespace


