
string[] ai_frameworks_list
string[] ai_frameworks_folder_list

string[] ai_frameworks_active_list


string[] ai_models_ordered_list
string[] ai_models_ordered_name_list
string[] ai_models_ordered_framework_list
string[] ai_models_ordered_type_list
AiModelStatus[] ai_models_ordered_status_list


string[] ai_models_active_list


string[] ai_models_running_list
string[] ai_models_running_name_list
string[] ai_models_running_type_list
string[] ai_models_running_namespace_list

bool retry_enabled

string all_namespace


