# This message details a navpose solution topic connection

string name 

string[] available_topics
string[] available_topic_msgs

# Value is updated when connected to data stream
# or manually set to some value
bool has_component

# If value is manually set
bool fixed

# If value set to topic
string topic
string topic_msg
string connected
float32 avg_rate
float32 last_time
Frame3DTransform transform




