## Pan Tilt offset msg
# Distances from pantilt base center mounting point
# to tilt axis center location
# Values are applied to NavPose data
# All values are ENU frame (x-forward,y-left,z-up)
# All values are in meters 
# All values should be taken in the pantilt upright position
# Inversions are handled by processes
float32 x_from_base_center
float32 y_from_base_center
float32 z_from_base_center

