# Process Connect Status Message

string node_name
string namespace

#################
# Process Settings
#################

##########
# Process
string[] available_processes
string selected_process
string process_topic
bool process_connected
nepi_interfaces/ProcessStatus process_status



###############
# Display Controls
###############
bool show_selection
bool show_sources
bool show_controls
bool show_results

