# Targeting Controls Status Message


string name
string namespace
bool enabled
string state
bool targeting_state

float32 max_update_rate_hz

string[] available_targets
string[] ordered_targets
string[] enabled_targets

string[] available_filters
string[] ordered_filters
string[] enabled_filters
string selected_filter

##################
string[] available_targeting_topics
string[] available_targeting_namespaces
string selected_targeting_topic
bool selected_targeting_connected

bool targeting_selected
bool targeting_connected







