# This message provides information for a single track event

float64 track_timestamp

string process_name
string process_namespace
string process_type
string process_description

string source_topic
string source_type
float64 source_timestamp
NavPose source_nav_pose

bool has_2d_data
bool has_3d_data
bool has_range_data
bool has_bearing_data
bool has_navpose_data
bool has_color_data
bool has_countour_data
bool has_shape_data

Target target