
---
bool sys_admin_enabled
bool sys_admin_password_valid
bool sys_admin_mode_set

bool sys_develop_enabled
bool sys_debug_enabled

string[] sys_managers_options
string[] sys_managers_enabled

DictString[] user_restrictions_options
string[] user_restrictions

string[] sys_run_mode_options
string sys_run_mode