
---

bool sys_debug_enabled

bool sys_admin_enabled
string sys_admin_password_encrypted

string[] sys_managers_options
string[] sys_managers_enabled

DictString[] user_restrictions_options
string[] user_restrictions

string[] sys_run_mode_options
string sys_run_mode