# This service definition provides the capabilities report for a NEPI IDX sensor

---
bool has_standby_mode


bool has_resolution
bool has_framerate
bool has_contrast
bool has_brightness
bool has_threshold
bool has_range
bool has_auto_adjust

bool has_color_image
bool has_bw_image
bool has_intensity_map
bool has_depth_map
bool has_pointcloud



# Data products supported by is a string of supported data products managed by node
#SUPPORTED_DATA_PRODUCTS = ['image','color_image','bw_image',
#                            'intensity_map','depth_map','pointcloud','navpose']
string[] data_products



