# This service definition provides the current list of IP addresses on the ethernet interface

---
# Array of CIDR-formatted ip addresses
string[] ip_addrs
string primary_ip_addr
string[] managed_ip_addrs
bool dhcp_enabled
string dhcp_ip_addr
bool internet_connected
