# This service provides the navpose data capabilities 

---

string navposes_topic
string[] navpose_frames
string[] navpose_frames_topics
string[] frame_nav_options
string[] frame_alt_options
string[] frame_depth_options

