# This service definition provides the navpose capabilities report for a general NEPI NPX driver node

---
bool has_heading
bool has_position
bool has_orientation
bool has_location
bool has_altitude
bool has_depth

bool supports_transform_updates

float32[] pub_rate_min_max

string[] data_products


