# This service definition provides the capabilities report for a NEPI PTX (pan/tilt) actuator

---
bool has_absolute_positioning
bool has_timed_positioning
bool has_seperate_pan_tilt_control
bool has_position_feedback
bool has_adjustable_speed
bool has_limit_controls
bool has_auto_pan
bool has_auto_tilt
bool has_auto_sin
bool has_homing
bool has_set_home

